[package]
name = "qmi"
authors = ["Glenn Wallace glennw-coding@proton.me"]
version = "0.0.1"
edition = "2024"
keywords = ["ecs"]
categories = ["game-development", "concurrency", "algorithms", "data-structures"]
license = "MIT"
repository = "https://github.com/Stack-Syndicate/qmi"

